[project]
name = "token-size"
version = "0.1.0"
description = "A Python project for token size utilities"
requires-python = ">=3.8"
dependencies = [
    "tiktoken",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_backend"
